environment:
  matrix:
  - TOXENV: "py34"
  - TOXENV: "py35"
  - TOXENV: "py36"
  - TOXENV: "py37"
  - TOXENV: "py38"

install:
  - C:\Python38\python -m pip install tox

build: false

test_script:
  - C:\Python38\python -m tox
