environment:
  matrix:
  - TOXENV: "py36"
  - TOXENV: "py37"
  - TOXENV: "py38"
  - TOXENV: "py39"
  - TOXENV: "py310"
  - TOXENV: "py311"
  - TOXENV: "py312"
  - TOXENV: "py313"

install:
  - C:\Python38\python -m pip install tox

build: false

test_script:
  - C:\Python38\python -m tox
